### PR TITLE
💥 Drop node 8 support 

### PR DESCRIPTION
**Pull request by dbendaou**
#### Description
This PR aims to drop `node 8` support as it has reaches is end of life
see https://nodejs.org/en/about/releases/

#### Changes
[//]: # "Add if relevant, remove if not"
* Update `package.json` to udpdate engines
* Update `.travis-ci.yml`

### CODE REVIEW

**Comment by aoumiri** [comment]
You need to also update the node version in https://github.com/qonto/ember-autofocus-modifier/blob/master/.github/workflows/ci.yml#L18

and above

**Comment by dcyriller** [comment]
We might want to remove .travis file (in an other PR?). Travis CI doesn't run anyway.

**Comment by dbendaou** [comment]
Done here https://github.com/qonto/ember-autofocus-modifier/pull/36

**Comment by dcyriller** [comment]
Thanks!

**Pull request merged**
